def get_cached_inputs():
    return [
        {
            "label": "surname?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "2",
        },
        {
            "label": "first name",
            "name": "",
            "fieldType": "select",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "1",
        },
        {
            "label": "phone",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "5",
        },
        {
            "label": "do you currently reside in or will you be relocating to any of the following states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "16",
        },
        {
            "label": "Do you now, or will you in the future, require sponsorship for employment visa status (e.g., H-1B visa status) to work legally for Samsung in United States of America?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "19",
        },
        {
            "label": "are you legally authorized to work in united states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "20",
        },
        {
            "label": " Are you a current university student?",
            "name": "",
            "fieldType": "radio",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "21",
        },
        {
            "label": "Start Date (year)",
            "name": "",
            "fieldType": "date",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "22",
        },
        {
            "label": "End Date (year)",
            "name": "",
            "fieldType": "date",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "23",
        },
        {
            "label": "When will you graduate? (expected month & year)",
            "name": "",
            "fieldType": "date",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "24",
        },
    ]
