def get_cached_inputs():
    return [
        {
            "label": "phone",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "5",
        },
        {
            "label": "website",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "15",
        },
        {
            "label": "do you currently reside in or will you be relocating to any of the following states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "16",
        },
        {
            "label": "do you currently reside in or will you be relocating to any of the following states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "18",
        },
        {
            "label": "will you now or in the future require visa sponsorship or a transfer for employment status (e.g., h-1b visa status)? if yes, please elaborate.",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "19",
        },
        {
            "label": "are you legally authorized to work in united states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "20",
        },
        {
            "label": "are you legally authorized to work in united states?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "22",
        },
        {
            "label": "how would you describe your gender identity?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "23",
        },
        {
            "label": "how would you describe your racial/ethnic background?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "25",
        },
        {
            "label": "how would you describe your sexual orientation?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "27",
        },
        {
            "label": "do you identify as transgender?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "29",
        },
        {
            "label": "do you have a disability or chronic condition (physical, visual, auditory, cognitive, mental, emotional, or other) that substantially limits one or more of your major life activities, including mobility, communication (seeing, hearing, speaking), and learning?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "31",
        },
        {
            "label": "are you a veteran or active member of the united states armed forces?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "33",
        },
        {
            "label": "gender",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "35",
        },
        {
            "label": "are you hispanic/latino?",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "37",
        },
        {
            "label": "veteran status",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "39",
        },
        {
            "label": "disability status",
            "name": "",
            "fieldType": "text",
            "wholeQuestionLabel": None,
            "value": "false",
            "id": "41",
        },
    ]
