// Events enum
export const eventTypes = {
  BEGIN_AUTHENTICATION_FLOW: 'BEGIN_AUTHENTICATION_FLOW',
  GET_AUTOFILL_VALUES: 'GET_AUTOFILL_VALUES',
  GET_SIMPLE_AUTOFILL_VALUES: 'GET_SIMPLE_AUTOFILL_VALUES',
  SAVE_AUTOFILL_VALUES: 'SAVE_AUTOFILL_VALUES',
  UPLOAD_RESUME: 'UPLOAD_RESUME',
  RETRIEVE_USER_DATA: 'RETRIEVE_USER_DATA',
  GET_TAILORING_QUESTIONS: 'GET_TAILORING_QUESTIONS',
  CONVERT_DOCX_TO_PDF: 'CONVERT_DOCX_TO_PDF',
  BEGIN_AUTOFILL_WITH_IFRAMES: 'BEGIN_AUTOFILL',
  AUTOFILL_WITH_IFRAMES_COMPLETED: 'AUTOFILL_WITH_IFRAMES_COMPLETED',
  BEGIN_RESUME_AUTOFILL: 'BEGIN_RESUME_AUTOFILL',
}
